import { expect, test, type Page } from '@playwright/test'

async function login(page: Page, role: 'admin' | 'clover' | 'demo') {
  await page.goto('/login')
  await page.getByLabel('Email', { exact: true }).fill(`${role}@calisapp.com`)
  await page.getByLabel('Contraseña', { exact: true }).fill(role === 'admin' ? 'Admin123!' : role === 'clover' ? 'Clover1234!' : 'Demo1234!')
  await page.getByRole('button', { name: 'Log In', exact: true }).click()
  await expect(page).not.toHaveURL(/\/login$/)
  await expect(page.getByRole('navigation', { name: 'Navegación principal' })).toBeVisible()
}

async function logout(page: Page) {
  await page.goto('/profile')
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page).toHaveURL(/\/login$/)
}

test('Guerrero consulta reseñas; comunidad privada bloqueada en UI y API', async ({ page }) => {
  await login(page, 'demo')
  await page.getByRole('link', { name: 'Comunidad', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Comunidad', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Quiero ser Clover' })).toBeVisible()
  await expect(page.getByText('Reseña de demostración:', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Novedades', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Bienvenidos a nuestra comunidad' })).toHaveCount(0)
  await page.goto('/admin/community')
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/community?tab=reviews')
  await expect(page.getByText('Reseña de demostración:', { exact: false })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: test.info().outputPath('guerrero-reviews.png'), fullPage: true })
})

test('Admin publica y edita; Clover reacciona; cambiar de cuenta limpia el contenido', async ({ page }) => {
  const title = `Encuentro E2E ${Date.now()}`
  await login(page, 'admin')
  await page.goto('/admin/community/posts/new')
  await page.getByLabel('Título', { exact: true }).fill(title)
  await page.getByLabel('Contenido', { exact: false }).fill('Nos encontramos para celebrar los avances del equipo.')
  await page.getByRole('button', { name: 'Publicar', exact: true }).click()
  await expect(page).toHaveURL(/\/community\/posts\/\d+$/)
  const postUrl = page.url()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  await page.getByRole('link', { name: 'Editar publicación' }).click()
  await page.getByLabel('Contenido', { exact: false }).fill('Novedad actualizada desde el panel de administración.')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page).toHaveURL(/\/community\/posts\/\d+$/)
  await expect(page.getByText('Novedad actualizada desde el panel de administración.')).toBeVisible()
  await logout(page)
  await login(page, 'clover')
  await page.goto(postUrl)
  await page.getByRole('button', { name: `Dar me gusta a ${title}` }).click()
  await expect(page.getByRole('button', { name: `Quitar me gusta a ${title}` })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: `Quitar me gusta a ${title}` }).click()
  await expect(page.getByRole('button', { name: `Dar me gusta a ${title}` })).toHaveAttribute('aria-pressed', 'false')
  await page.goto('/community')
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  await expect(page.getByText('Novedad actualizada desde el panel de administración.')).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('clover-feed.png'), fullPage: true })
  await logout(page)
  await login(page, 'demo')
  await page.goto('/community?tab=posts')
  await expect(page.getByRole('heading', { name: title })).toHaveCount(0)
  await page.goto(postUrl)
  await expect(page).toHaveURL(/\/$/)
  await logout(page)
  await login(page, 'admin')
  await page.goto(postUrl)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Retirar publicación' }).click()
  await expect(page).toHaveURL(/\/community$/)
  await expect(page.getByRole('heading', { name: title })).toHaveCount(0)
})

test('Admin crea un evento; Clover reserva y cancela; se conserva el historial', async ({ page }) => {
  const title = `Taller E2E ${Date.now()}`
  await login(page, 'admin')
  await page.goto('/admin/community/events/new')
  await page.getByLabel('Título', { exact: true }).fill(title)
  await page.getByLabel('Descripción', { exact: true }).fill('Técnica de dominadas en equipo.')
  await page.getByLabel('Lugar', { exact: true }).fill('Sala principal')
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10)
  await page.getByLabel('Inicio (hora local)').fill(`${tomorrow}T15:00`)
  await page.getByLabel('Finalización (hora local)').fill(`${tomorrow}T17:00`)
  await page.getByLabel('Cupo máximo', { exact: false }).fill('2')
  await page.getByRole('button', { name: 'Crear evento', exact: true }).click()
  await expect(page).toHaveURL(/\/community\/events\/\d+$/)
  const eventUrl = page.url()
  await logout(page)
  await login(page, 'clover')
  await page.goto(eventUrl)
  await page.getByRole('button', { name: 'Anotarme al evento' }).click()
  await expect(page.getByText('Tu lugar está confirmado.')).toBeVisible()
  await page.getByRole('button', { name: 'Cancelar mi inscripción' }).click()
  await expect(page.getByRole('button', { name: 'Anotarme al evento' })).toBeVisible()
  await logout(page)
  await login(page, 'admin')
  await page.goto(eventUrl)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Cancelar evento', exact: true }).click()
  await expect(page.getByText('Este evento fue cancelado por el gimnasio.')).toBeVisible()
  await page.goto('/community?tab=events')
  await page.getByRole('button', { name: 'Historial', exact: true }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
})

test('Reseña editable, moderación reversible y caché PWA sin contenido privado', async ({ page, context }) => {
  await login(page, 'clover')
  await page.goto('/community?tab=reviews')
  await page.getByRole('link', { name: 'Clase de demostración — fundamentos', exact: true }).first().click()
  await page.getByRole('radio', { name: '4 estrellas', exact: true }).check()
  await page.getByRole('button', { name: 'Actualizar reseña' }).click()
  await expect(page.getByText('Tu reseña fue guardada.')).toBeVisible()
  await page.goto('/community')
  await expect(page.getByRole('heading', { name: 'Bienvenidos a nuestra comunidad' })).toBeVisible()
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  const cachedPrivateUrls = await page.evaluate(async () => {
    const keys = await caches.keys()
    const urls = (await Promise.all(keys.map(async key => (await (await caches.open(key)).keys()).map(r => r.url)))).flat()
    return urls.filter(url => /\/api\/(post|event|review|media)(\/|\?|$)/.test(url) || url.includes('.r2.cloudflarestorage.com'))
  })
  expect(cachedPrivateUrls).toEqual([])
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Eventos', exact: true }).click()
  await expect(page.getByText('Estás sin conexión. El contenido exclusivo requiere internet.')).toBeVisible()
  await context.setOffline(false)
  await logout(page)
  await login(page, 'admin')
  await page.goto('/admin/community')
  const review = page.locator('article').filter({ hasText: 'Reseña de demostración:' }).first()
  await review.getByRole('button', { name: 'Retirar reseña' }).click()
  await expect(review.getByText('Retirada por moderación')).toBeVisible()
  await review.getByRole('button', { name: 'Restaurar reseña' }).click()
  await expect(review.getByRole('button', { name: 'Retirar reseña' })).toBeVisible()
  await page.setViewportSize({ width: 844, height: 390 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: test.info().outputPath('admin-landscape.png'), fullPage: true })
})
